# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yCy85Agzi4w2pgnDwv2oDSicaA6dz3hY
"""

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# Define the filenames of the input png files
filenames = [
    # 'K1.png', 'K2.png', 'K3.png', 'K4.png',
    # 'KK_1.png', 'KK_2.png', 'KK_3.png', 'KK_4.png',
    # 'TS_K_1.png', 'TS_K_2.png', 'TS_K_3.png', 'TS_K_4.png'
    # 'D1.png', 'D2.png', 'D3.png', 'D4.png',
    # 'DD_1.png', 'DD_2.png', 'DD_3.png', 'DD_4.png',
    # 'TS_D_1.png', 'TS_D_2.png', 'TS_D_3.png', 'TS_D_4.png',
    'K_total.png', 'D_total.png',
     'K_TT.png', 'corrected_cluster.png',
      'TS_K_TT.png', 'corrected_tsne.png'
]

# Create a figure with subplots arranged in a (6,4) matrix
fig, axs = plt.subplots(3, 2, figsize=(12, 4))

# Set the titles for the subplots
titles = [
    # 'K-Means DB score (1st Dec - 15 Feb) ', 'K-Means DB score (15 Feb - 15 June)', 'K-Means DB score (15 June - 15 Oct) ', 'K-Means  Dec DB score (15 Oct - 31st Dec)',
    # 'K-Means  Cluster', 'K-Means  Cluster', 'K-Means  Cluster', 'K-Means  Cluster',
    # 'K-Means  with T-SNE validation', 'K-Means  with T-SNE validation', 'K-Means with T-SNE validation', 'K-Means  with T-SNE validation',
    # 'DBSCAN -  DB score(1st Dec - 15 Feb)', 'DBSCAN -  DB score(15 Feb - 15 June)', 'DBSCAN -  DB score(15 June - 15 Oct)', 'DBSCAN -  DB score(15 Oct - 31st Dec)',
    # 'DBSCAN  Cluster', 'DBSCAN Cluster', 'DBSCAN  Cluster', 'DBSCAN  Cluster',
    # 'DBSCAN  with T-SNE validation', 'DBSCAN  with T-SNE validation', 'DBSCAN  with T-SNE validation', 'DBSCAN with T-SNE validation',
    'K-Means  DB score', 'DBSCAN DB score',
    'K-Means  Cluster', 'DBSCAN Cluster',
    'K-Means  with T-SNE validation', 'DBSCAN  with T-SNE validation',
]

# Load and display the png files in each subplot
for i, filename in enumerate(filenames):
    img = mpimg.imread(filename)
    axs[i//2, i%2].imshow(img)
    axs[i//2, i%2].axis('off') 
    axs[i//2, i%2].set_title(titles[i], fontsize=8)

# Show the plot
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# Define the filenames of the input png files
filenames = [
    'K1.png', 'K2.png', 'K3.png', 'K4.png',
    'KK_1.png', 'KK_2.png', 'KK_3.png', 'KK_4.png',
    'TS_K_1.png', 'TS_K_2.png', 'TS_K_3.png', 'TS_K_4.png',
    'D1.png', 'D2.png', 'D3.png', 'D4.png',
    'DD_1.png', 'DD_2.png', 'DD_3.png', 'DD_4.png',
    'TS_D_1.png', 'TS_D_2.png', 'TS_D_3.png', 'TS_D_4.png',
]

# Create a figure with subplots arranged in a (6,4) matrix
fig, axs = plt.subplots(6, 4, figsize=(12, 6))

# Set the titles for the subplots
for i in range(4):
    axs[0, i].set_title('K-Means')
    axs[1, i].set_title('DBSCAN')
    
for i in range(6):
    axs[i, 0].set_ylabel('{}'.format(i+1))
    
for i in range(4):
    axs[5, i].set_xlabel('{}'.format(i+1))

# Load and display the png files in each subplot
for i, filename in enumerate(filenames):
    img = mpimg.imread(filename)
    axs[i//4, i%4].imshow(img)
    axs[i//4, i%4].axis('off') 

# Show the plot
plt.show()